version: "3.8"
services:
  app:
    build:
      context: .
    ports:
      - '5000:5000'
    depends_on:
      postgres:
        condition: service_healthy
      make_migrations:
        condition: service_completed_successfully
    volumes:
      - ./config.py:/skywars/config.py
      - ./admin.json:/skywars/data/admin.json
      - ./logs.txt:/skywars/data/logs.txt

  make_migrations:
    build:
      context: .
    depends_on:
      postgres:
        condition: service_healthy
    command: python3 create_db.py
    volumes:
      - ./admin.json:/skywars/data/admin.json
      - ./config.py:/skywars/config.py

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: skywars_data
      POSTGRES_PASSWORD: LegatCalibra47960805
      POSTGRES_USER: plamer777
    ports:
      - '5432:5432'
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready --username=plamer777 -d skywars_data']
      interval: 5s
      timeout: 10s
      retries: 5
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
